when:
  event:
    - manual

steps:
  run-tests:
    image: mcr.microsoft.com/playwright:v1.48.0-jammy
    environment:
      CI_REPO_ID: ${CI_REPO_REMOTE_ID}
      CI_BUILD_NUMBER: ${CI_PIPELINE_NUMBER}
    commands:
      - chmod +x scripts/run_playwright.sh
      - ./scripts/run_playwright.sh "$CI_REPO_ID" "$CI_BUILD_NUMBER"
    failure: ignore

  upload:
    image: woodpeckerci/plugin-s3
    settings:
      bucket: manaable
      access_key: manaable
      secret_key: manaable
      source: repos/**/*
      target: /
      path_style: true
      endpoint: http://192.168.1.15:9001
    depends_on:
      - run-tests

  # export-artifacts:
  #   image: alpine
  #   environment:
  #       CI_REPO_NAME: ${CI_REPO_NAME}
  #       CI_BUILD_NUMBER: ${CI_BUILD_NUMBER}
  #   privileged: true
  #   volumes:
  #     - /ci-shared:/ci-shared
  #   commands:
  #     - mkdir -p "/ci-shared/playwright/${CI_REPO_NAME}/build-${CI_BUILD_NUMBER}"
  #     - cp test-results.json "/ci-shared/playwright/${CI_REPO_NAME}/build-${CI_BUILD_NUMBER}/summary.json" || true
  #     - cp -r playwright-report "/ci-shared/playwright/${CI_REPO_NAME}/build-${CI_BUILD_NUMBER}/playwright-report" || true

